"""empty message

Revision ID: 8acb93c949e6
Revises: 
Create Date: 2023-07-26 15:22:20.176435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8acb93c949e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('plate_no', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_address', sa.String(), nullable=False),
    sa.Column('owner_dl_number', sa.String(), nullable=False),
    sa.Column('checkin_at', sa.DateTime(), nullable=True),
    sa.Column('checkout_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker_assignment',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('worker_id', 'car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_assignment')
    op.drop_table('workers')
    op.drop_table('cars')
    # ### end Alembic commands ###
